# Site settings
title: Chase Kregor's Website
description: Chase Kregor's blog
# url: "chasekregor.com"
permalink: pretty

# Sass
sass:
    sass_dir: _sass

# Navigation Bar
# navigation-header:
#   Home: /
#   Posts: /posts/
#   Categories: /Categories/
#   Projects: /projects/

# User settings
username: Chase Kregro
user_title: Data Scientist
email: chaseakregor@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
